[package]
name = "mosdev"
version = "0.1.0"
authors = ["Roy Jacobs <rjacobs@bol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
#structopt = "0.3"